development:
  adapter: postgresql
  encoding: unicode
  database: auth_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: auth_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres